export type Slot = "GR"|"LD"|"DC"|"LE"|"MD"|"MC"|"MO"|"ED"|"EE"|"PL"|"AD"|"AE";
export type Player = { id:string; name:string; era:string; positions:Slot[]; benfica:number; career:number; traits:string[]; note:string };
type R = [string,string,string,Slot[],number,number,string[],string];
const raw:R[]=[
["costa-pereira","Costa Pereira","1954–67",["GR"],96,92,["Muralha","Noite europeia"],"A segurança dos primeiros campeões europeus."],
["bento","Manuel Bento","1972–92",["GR"],96,91,["Muralha","Capitão"],"Duas décadas de reflexos e liderança."],
["preudhomme","Michel Preud'homme","1994–99",["GR"],95,95,["Muralha"],"Classe mundial numa equipa em reconstrução."],
["oblak","Jan Oblak","2010–14",["GR"],84,96,["Muralha"],"Pouco tempo, uma reta final quase perfeita."],
["ederson","Ederson","2015–17",["GR"],87,94,["Construtor"],"O ataque começava nos seus pés."],
["cavem","Mário João Cavém","1955–69",["LD","LE","MD"],94,90,["Polivalente","Noite europeia"],"Tudo o que a equipa precisasse."],
["angelo","Ângelo Martins","1952–65",["LD","DC"],94,89,["Muralha","Noite europeia"],"Incansável nos bicampeões da Europa."],
["germano","Germano","1960–66",["DC","MD"],96,94,["Capitão","Muralha"],"O patrão defensivo dos anos de ouro."],
["humberto","Humberto Coelho","1968–84",["DC"],97,94,["Capitão","Muralha"],"Elegância, antecipação e comando."],
["artur","Artur Correia","1971–77",["LD","DC"],91,90,["Pulmão"],"Lateral moderno antes do tempo."],
["veloso","António Veloso","1980–95",["LE","LD","DC"],94,90,["Capitão","Muralha"],"Rigor e quinze épocas de Benfica."],
["mozer","Carlos Mozer","1987–92",["DC"],93,92,["Muralha"],"Intensidade e autoridade."],
["ricardo-gomes","Ricardo Gomes","1988–91",["DC"],92,93,["Muralha","Noite europeia"],"Central de elite e finalista europeu."],
["aldair","Aldair","1989–90",["DC"],80,96,["Muralha"],"Uma época na Luz, uma carreira gigante."],
["luisao","Luisão","2003–18",["DC"],97,91,["Capitão","Rei da Luz"],"Quinze anos e símbolo de uma era."],
["garay","Ezequiel Garay","2011–14",["DC"],91,92,["Muralha","Noite europeia"],"Classe numa defesa dominante."],
["coentrao","Fábio Coentrão","2007–11",["LE","AE"],91,91,["Rutura","Pulmão"],"Explosão e profundidade."],
["maxi","Maxi Pereira","2007–15",["LD","AD"],91,88,["Pulmão"],"Competitividade permanente."],
["ruben","Rúben Dias","2017–20",["DC"],87,95,["Capitão","Formação"],"Líder criado no Seixal."],
["coluna","Mário Coluna","1954–70",["MC","MD","MO"],99,97,["Capitão","Pulmão","Noite europeia"],"O Monstro Sagrado."],
["jaime-graca","Jaime Graça","1966–75",["MC","MO"],94,91,["Maestro"],"Inteligência entre linhas."],
["toni","Toni","1968–81",["MC","MD"],96,91,["Capitão","Pulmão"],"Cérebro competitivo."],
["sheu","Shéu Han","1972–89",["MC","MD"],95,89,["Capitão","Pulmão"],"Lealdade e equilíbrio."],
["chalana","Fernando Chalana","1976–90",["EE","ED","MO"],98,92,["Maestro","Rutura","Rei da Luz"],"O Pequeno Genial."],
["joao-alves","João Alves","1975–83",["MC","MO"],94,92,["Maestro"],"Luvas pretas, raro sentido de jogo."],
["rui-costa","Rui Costa","1990–2008",["MO","MC"],94,97,["Maestro","Rei da Luz"],"Visão, passe e identidade."],
["valdo","Valdo","1988–95",["MO","MC"],93,93,["Maestro","Noite europeia"],"Elegância em duas finais europeias."],
["isaias","Isaías","1990–95",["MO","ED","PL"],93,88,["Matador","Noite europeia"],"Remate brutal contra gigantes."],
["aimar","Pablo Aimar","2008–13",["MO","MC"],92,95,["Maestro","Rei da Luz"],"Talento puro ao serviço da equipa."],
["enzo","Enzo Pérez","2011–14",["MC","MD","AD"],91,91,["Pulmão","Noite europeia"],"Pressão, transporte e intensidade."],
["matic","Nemanja Matić","2011–14",["MD","MC"],90,94,["Muralha","Pulmão"],"Dimensão de gigante no meio."],
["pizzi","Pizzi","2014–22",["MC","MO","AD","ED"],92,87,["Maestro","Rei da Luz"],"Golos, assistências e ligação com Jonas."],
["di-maria","Ángel Di María","2007–24",["ED","EE","MO"],90,98,["Maestro","Rutura","Noite europeia"],"Irreverência e classe mundial."],
["bernardo","Bernardo Silva","2013–15",["MO","MC","ED"],73,97,["Maestro","Formação"],"Carreira enorme, pouca equipa principal."],
["eusebio","Eusébio","1960–75",["PL","EE"],100,100,["Matador","Rutura","Noite europeia","Rei da Luz"],"A Pantera Negra. O teto do jogo."],
["jose-aguas","José Águas","1950–63",["PL"],98,95,["Matador","Capitão"],"Levantou duas Taças dos Campeões."],
["jose-augusto","José Augusto","1959–69",["ED","PL"],96,94,["Rutura","Matador"],"Velocidade e golo na geração dourada."],
["simoes","António Simões","1961–75",["EE","AE"],97,94,["Rutura","Maestro"],"Extremo de classe mundial."],
["torres","José Torres","1959–71",["PL"],96,94,["Matador","Noite europeia"],"O Bom Gigante."],
["nene","Nené","1968–86",["PL","ED"],98,93,["Matador","Rei da Luz"],"Dezoito épocas a marcar."],
["vitor-baptista","Vítor Baptista","1971–78",["PL","MO"],92,89,["Matador","Maestro"],"Génio imprevisível."],
["nuno-gomes","Nuno Gomes","1997–2011",["PL"],95,92,["Matador","Rei da Luz"],"Golo e ligação emocional à Luz."],
["jvp","João Vieira Pinto","1992–2000",["MO","PL","ED"],97,93,["Maestro","Matador","Rei da Luz"],"O menino de ouro dos anos 90."],
["simao","Simão Sabrosa","2001–07",["EE","ED","MO"],97,94,["Capitão","Rutura","Noite europeia"],"O Benfica renasceu com ele."],
["cardozo","Óscar Cardozo","2007–14",["PL"],96,89,["Matador","Noite europeia","Rei da Luz"],"Tacuara: remate e frieza."],
["jonas","Jonas","2014–19",["PL","MO"],99,86,["Matador","Maestro","Rei da Luz"],"No Benfica foi extraordinário."],
["saviola","Javier Saviola","2009–12",["PL","MO"],90,93,["Maestro","Rutura"],"Entendimento telepático com Aimar."],
["gaitan","Nicolás Gaitán","2010–16",["EE","ED","MO"],96,89,["Maestro","Noite europeia"],"Derrubava blocos europeus."],
["rafa","Rafa Silva","2016–24",["EE","ED","MO"],92,89,["Rutura","Rei da Luz"],"Aceleração devastadora."],
["lima","Lima","2012–15",["PL"],91,87,["Matador","Pulmão"],"Mobilidade e golos europeus."],
["jose-henrique","José Henrique","1966–79",["GR"],93,88,["Muralha","Noite europeia"],"Uma década de segurança entre os postes."],
["silvino","Silvino Louro","1984–94",["GR"],88,86,["Muralha"],"Fiável numa era de grandes noites europeias."],
["enke","Robert Enke","1999–2002",["GR"],88,91,["Muralha"],"Talento e personalidade num Benfica difícil."],
["julio-cesar","Júlio César","2014–17",["GR"],90,94,["Muralha","Noite europeia"],"Experiência de campeão ao serviço do tetra."],
["vlachodimos","Odysseas Vlachodimos","2018–23",["GR"],88,86,["Muralha"],"Reflexos decisivos em várias campanhas europeias."],
["pietra","Minervino Pietra","1976–87",["LD","DC"],93,88,["Pulmão","Muralha"],"Regularidade e entrega no corredor direito."],
["bastos-lopes","Bastos Lopes","1972–84",["DC","LD"],92,87,["Muralha","Noite europeia"],"Central sereno de um Benfica dominante."],
["alvaro","Álvaro Magalhães","1981–90",["LE","AE"],93,88,["Pulmão","Rutura"],"Intensidade total no lado esquerdo."],
["schwarz","Stefan Schwarz","1990–94",["LE","DC","MD"],89,92,["Polivalente","Pulmão"],"Potência, técnica e enorme versatilidade."],
["leo","Léo","2005–09",["LE","AE"],91,87,["Pulmão","Rei da Luz"],"Pequeno no corpo, enorme na entrega."],
["gamarra","Carlos Gamarra","1997–2000",["DC"],90,95,["Muralha","Capitão"],"Leitura defensiva de nível mundial."],
["david-luiz","David Luiz","2007–11",["DC","MD"],88,94,["Construtor","Rutura"],"Atrevimento e saída de bola desde trás."],
["jardel","Jardel","2011–21",["DC"],91,86,["Muralha","Capitão"],"De suplente a pilar de quatro campeonatos."],
["lindelof","Victor Lindelöf","2012–17",["DC","LD"],86,91,["Construtor","Formação"],"Evoluiu no Seixal até comandar a defesa."],
["antonio-silva","António Silva","2022–26",["DC"],86,90,["Construtor","Formação"],"Central de elite lançado ainda adolescente."],
["cancelo","João Cancelo","2012–14",["LD","AD","ED"],70,96,["Rutura","Formação","Polivalente"],"Pouca equipa principal; carreira de topo mundial."],
["nelson-semedo","Nélson Semedo","2015–17",["LD","AD"],86,91,["Rutura","Formação"],"Verticalidade criada no Seixal."],
["grimaldo","Álex Grimaldo","2016–23",["LE","AE"],94,92,["Maestro","Rutura","Rei da Luz"],"Um lateral que construía como médio."],
["andre-almeida","André Almeida","2011–22",["LD","LE","DC"],89,84,["Polivalente","Capitão"],"Disponibilidade total para a equipa."],
["miguel","Miguel","2000–05",["LD","AD"],90,92,["Rutura","Pulmão"],"Um extremo transformado em lateral explosivo."],
["paulo-madeira","Paulo Madeira","1989–2002",["DC"],89,86,["Muralha","Formação"],"Produto da casa e presença longa no eixo."],
["helder","Hélder Cristóvão","1992–2002",["DC","LE"],88,87,["Muralha","Polivalente"],"Força e compromisso numa década instável."],
["tahar","Tahar El Khalej","2000–04",["DC","MD"],86,86,["Muralha","Polivalente"],"Combatividade e experiência no centro."],
["fernando-meira","Fernando Meira","1996–2002",["DC","MD"],87,93,["Construtor","Formação"],"Formado na Luz, afirmou-se ao mais alto nível."],
["carlos-manuel","Carlos Manuel","1979–87",["MC","MO"],96,92,["Maestro","Noite europeia","Capitão"],"Meio-campo total e golos que ficaram na história."],
["diamantino","Diamantino Miranda","1977–90",["MO","ED","EE"],94,88,["Maestro","Rutura"],"Técnica e irreverência entre duas gerações."],
["petit","Petit","2002–07",["MD","MC"],92,89,["Pulmão","Capitão"],"Pressão, remate e coração no renascimento."],
["katsouranis","Kostas Katsouranis","2006–09",["MD","MC","DC"],88,91,["Polivalente","Pulmão"],"Inteligência tática em várias posições."],
["javi-garcia","Javi García","2009–12",["MD","MC"],90,90,["Muralha","Pulmão"],"O tampão do primeiro grande Benfica de Jesus."],
["fejsa","Ljubomir Fejsa","2013–19",["MD"],92,87,["Muralha","Rei da Luz"],"Equilíbrio invisível em cinco campeonatos."],
["witsel","Axel Witsel","2011–12",["MC","MD"],86,94,["Pulmão","Construtor"],"Uma época bastou para mostrar classe mundial."],
["ramires","Ramires","2009–10",["MC","AD"],88,94,["Pulmão","Rutura"],"O Queniano cobria o campo inteiro."],
["andre-gomes","André Gomes","2012–14",["MC","MO"],81,93,["Maestro","Formação"],"Formação Benfica e carreira internacional sólida."],
["renato","Renato Sanches","2015–22",["MC","MD"],87,92,["Pulmão","Formação","Rutura"],"Energia adolescente para mudar um campeonato."],
["florentino","Florentino Luís","2018–26",["MD","MC"],89,88,["Muralha","Formação"],"Recuperação de bola e leitura do espaço."],
["joao-mario","João Mário","2021–24",["MC","MO","AD"],88,90,["Maestro","Polivalente"],"Controlo, chegada à área e uma época memorável."],
["salvio","Eduardo Salvio","2010–19",["ED","AD"],94,89,["Rutura","Rei da Luz"],"O Toto atacava cada duelo sem medo."],
["miccoli","Fabrizio Miccoli","2005–07",["PL","EE"],89,93,["Matador","Rutura","Rei da Luz"],"Pouco tempo, golos de culto e enorme talento."],
["mitroglou","Kostas Mitroglou","2015–17",["PL"],94,89,["Matador","Rei da Luz"],"Quarenta e muitos golos no coração do tetra."],
["mantorras","Pedro Mantorras","2001–11",["PL"],92,84,["Matador","Rei da Luz"],"Um símbolo de esperança e resistência."],
["magnusson","Mats Magnusson","1987–92",["PL"],93,88,["Matador","Noite europeia"],"Goleador sueco de duas finais europeias."],
["cesar-brito","César Brito","1989–95",["PL","ED"],91,86,["Matador","Rutura"],"Velocidade e dois golos eternos em Highbury."],
["van-hooijdonk","Pierre van Hooijdonk","2000–01",["PL"],87,92,["Matador"],"Uma temporada, muitos golos e livre direto temível."],
["raul-jimenez","Raúl Jiménez","2015–18",["PL"],86,93,["Matador","Pulmão"],"Suplente decisivo antes de brilhar em Inglaterra."],
["darwin","Darwin Núñez","2020–22",["PL","EE"],89,93,["Rutura","Matador"],"Potência e golos numa grande campanha europeia."],
["goncalo-ramos","Gonçalo Ramos","2020–23",["PL"],88,91,["Matador","Formação","Pulmão"],"Pressão e finalização moldadas no Seixal."],
["joao-felix","João Félix","2018–19",["MO","PL","EE"],89,93,["Maestro","Formação","Rutura"],"Uma época de explosão e talento raro."],
["goncalo-guedes","Gonçalo Guedes","2014–26",["EE","ED","PL"],85,91,["Rutura","Formação"],"Potência criada no Seixal e regresso à casa."],
["derlei","Derlei","2007–09",["PL","EE"],84,91,["Pulmão","Matador"],"Sacrifício, experiência europeia e trabalho."],
["vata","Vata","1988–91",["PL","EE"],91,85,["Matador","Noite europeia"],"O golo que levou o Benfica à final de 1990."],
];
export const players:Player[]=raw.map(([id,name,era,positions,benfica,career,traits,note])=>({id,name,era,positions,benfica,career,traits,note}));
export const rating=(p:Player)=>Math.round(p.benfica*.6+p.career*.4);
export type Coach={id:string;name:string;era:string;rating:number;style:string;bonus:string;trait:"ataque"|"defesa"|"controlo"|"europa"};
export const coaches:Coach[]=[
{id:"guttmann",name:"Béla Guttmann",era:"1959–62",rating:97,style:"Coragem europeia",bonus:"+4 nas eliminatórias",trait:"europa"},
{id:"hagan",name:"Jimmy Hagan",era:"1970–73",rating:93,style:"Pressão e disciplina",bonus:"+3 controlo",trait:"controlo"},
{id:"otto",name:"Otto Glória",era:"1954–70",rating:92,style:"Modernização",bonus:"+3 equilíbrio",trait:"controlo"},
{id:"eriksson",name:"Sven-Göran Eriksson",era:"1982–92",rating:93,style:"Organização europeia",bonus:"+3 defesa",trait:"defesa"},
{id:"mortimore",name:"John Mortimore",era:"1976–87",rating:89,style:"Consistência",bonus:"+3 estabilidade",trait:"controlo"},
{id:"toni",name:"Toni",era:"1987–2000",rating:90,style:"Identidade Benfica",bonus:"+4 química na Luz",trait:"controlo"},
{id:"trap",name:"Giovanni Trapattoni",era:"2004–05",rating:88,style:"Pragmatismo",bonus:"+4 defesa",trait:"defesa"},
{id:"camacho",name:"José A. Camacho",era:"2002–08",rating:87,style:"Intensidade",bonus:"+3 duelos",trait:"controlo"},
{id:"jesus",name:"Jorge Jesus",era:"2009–20",rating:94,style:"Ataque posicional",bonus:"+4 ataque",trait:"ataque"},
{id:"vitoria",name:"Rui Vitória",era:"2015–19",rating:88,style:"Talento jovem",bonus:"+3 à formação",trait:"controlo"}];
export const formations={"4-3-3":["GR","LE","DC","DC","LD","MC","MC","MO","EE","PL","ED"],"4-2-3-1":["GR","LE","DC","DC","LD","MD","MC","EE","MO","ED","PL"],"4-4-2 D":["GR","LE","DC","DC","LD","MD","MC","MC","MO","PL","PL"],"3-4-3":["GR","DC","DC","DC","AE","MC","MC","AD","EE","PL","ED"]} satisfies Record<string,Slot[]>;
export type Formation=keyof typeof formations;
export const links=[[["eusebio","coluna"],"Eixo bicampeão europeu",9],[["eusebio","torres"],"Pantera & Bom Gigante",6],[["chalana","nene"],"Génio e finalização",5],[["jvp","isaias"],"Ouro e canhão",7],[["rui-costa","nuno-gomes"],"Maestro & ponta",6],[["simao","nuno-gomes"],"Capitães do renascimento",5],[["aimar","saviola"],"Dupla de sonho argentina",9],[["aimar","cardozo"],"Passe e martelo",7],[["luisao","garay"],"Muralha de 2014",7],[["luisao","jardel"],"Torres do tetra",5],[["enzo","matic"],"Meio-campo de 2014",7],[["gaitan","cardozo"],"Criação e finalização",6],[["gaitan","salvio"],"Alas de 2014",5],[["jonas","pizzi"],"Sociedade do tetra",9],[["jonas","mitroglou"],"Golos do tetra",7],[["bernardo","cancelo"],"Geração 94",5],[["renato","fejsa"],"Equilíbrio do tri",5]] as [string[],string,number][];
export type Rival={id:string;name:string;edition:string;rating:number;att:number;mid:number;def:number;identity:string;core:string;colors:[string,string];current?:boolean};
export const rivals:Rival[]=[
{id:"celtic",name:"Celtic",edition:"1966/67",rating:90,att:92,mid:90,def:89,identity:"Ataque incessante",core:"Johnstone · Wallace · Murdoch · McNeill",colors:["#17834b","#f4efe2"]},
{id:"ajax",name:"Ajax",edition:"1971/72",rating:94,att:96,mid:95,def:91,identity:"Futebol total",core:"Cruyff · Neeskens · Krol · Haan",colors:["#d62032","#f4efe2"]},
{id:"porto",name:"FC Porto",edition:"2003/04",rating:91,att:90,mid:93,def:92,identity:"Detalhe tático",core:"Deco · Maniche · Carvalho · Vítor Baía",colors:["#14529a","#f4efe2"]},
{id:"inter",name:"Inter",edition:"2009/10",rating:94,att:94,mid:93,def:97,identity:"Organização e transição",core:"Milito · Sneijder · Zanetti · Lúcio",colors:["#123e78","#171717"]},
{id:"real",name:"Real Madrid",edition:"2016/17",rating:97,att:98,mid:98,def:94,identity:"Autoridade europeia",core:"Ronaldo · Modrić · Kroos · Ramos",colors:["#eee8d9","#c7a34a"]},
{id:"psg",name:"Paris SG",edition:"2025/26",rating:96,att:97,mid:96,def:93,identity:"Pressão, posse e talento",core:"Dembélé · Vitinha · Kvaratskhelia · Hakimi",colors:["#13234b","#e4233f"],current:true},
{id:"barca",name:"Barcelona",edition:"2010/11",rating:97,att:98,mid:99,def:93,identity:"Posse sufocante",core:"Messi · Xavi · Iniesta · Busquets",colors:["#9d1736","#17448c"]},
{id:"milan",name:"AC Milan",edition:"1988/89",rating:96,att:96,mid:96,def:98,identity:"Bloco alto e defesa histórica",core:"Van Basten · Gullit · Rijkaard · Maldini",colors:["#b51f2e","#171717"]},
{id:"bayern",name:"Bayern",edition:"2019/20",rating:96,att:98,mid:95,def:94,identity:"Ritmo brutal",core:"Lewandowski · Müller · Kimmich · Neuer",colors:["#c9142d","#f5f1e8"]},
{id:"liverpool",name:"Liverpool",edition:"1983/84",rating:94,att:94,mid:95,def:93,identity:"Intensidade e controlo",core:"Dalglish · Rush · Souness · Hansen",colors:["#a41424","#f1d6a5"]},
{id:"united",name:"Man. United",edition:"1998/99",rating:94,att:96,mid:95,def:91,identity:"Até ao último segundo",core:"Yorke · Beckham · Keane · Schmeichel",colors:["#b9152b","#171717"]},
{id:"chelsea",name:"Chelsea",edition:"2011/12",rating:91,att:91,mid:91,def:94,identity:"Resistência extrema",core:"Drogba · Lampard · Terry · Čech",colors:["#17458c","#e8d39a"]},
{id:"juve",name:"Juventus",edition:"1995/96",rating:92,att:93,mid:92,def:93,identity:"Potência e maturidade",core:"Vialli · Del Piero · Deschamps · Peruzzi",colors:["#171717","#f1eee5"]},
{id:"dortmund",name:"Dortmund",edition:"1996/97",rating:91,att:92,mid:91,def:91,identity:"Pressão e energia",core:"Riedle · Möller · Sammer · Kohler",colors:["#f2d21d","#171717"]},
{id:"marseille",name:"Marseille",edition:"1992/93",rating:90,att:89,mid:91,def:92,identity:"Força e controlo",core:"Bokšić · Deschamps · Desailly · Barthez",colors:["#34a8d4","#f5f1e8"]},
{id:"forest",name:"Nott'm Forest",edition:"1979/80",rating:90,att:89,mid:90,def:93,identity:"Disciplina de campeão",core:"Francis · Robertson · McGovern · Shilton",colors:["#c3192d","#f4f0e6"]},
{id:"feyenoord",name:"Feyenoord",edition:"1969/70",rating:90,att:91,mid:90,def:90,identity:"Força coletiva neerlandesa",core:"Kindvall · Van Hanegem · Jansen · Israel",colors:["#d6212f","#f4f0e6"]},
{id:"villa",name:"Aston Villa",edition:"1981/82",rating:89,att:88,mid:89,def:93,identity:"Resistência e eficácia",core:"Withe · Morley · Cowans · Spink",colors:["#7b1641","#79b8dc"]},
{id:"hamburg",name:"Hamburgo",edition:"1982/83",rating:91,att:91,mid:92,def:92,identity:"Pressão e organização",core:"Hrubesch · Magath · Rolff · Stein",colors:["#1164a5","#f4f0e6"]},
{id:"steaua",name:"Steaua Bucareste",edition:"1985/86",rating:89,att:87,mid:89,def:94,identity:"Disciplina e penáltis",core:"Lăcătuș · Balint · Bölöni · Duckadam",colors:["#d92736","#1659a8"]},
{id:"psv",name:"PSV",edition:"1987/88",rating:91,att:90,mid:92,def:93,identity:"Equilíbrio total",core:"Kieft · Koeman · Lerby · Van Breukelen",colors:["#d71932","#f4f0e6"]},
{id:"red-star",name:"Estrela Vermelha",edition:"1990/91",rating:92,att:94,mid:93,def:90,identity:"Talento balcânico",core:"Pančev · Savićević · Prosinečki · Belodedici",colors:["#d51f35","#f4f0e6"]},
{id:"city",name:"Manchester City",edition:"2022/23",rating:96,att:98,mid:97,def:94,identity:"Controlo posicional",core:"Haaland · De Bruyne · Rodri · Rúben Dias",colors:["#74b9dc","#f4f0e6"]},
{id:"porto-87",name:"FC Porto",edition:"1986/87",rating:91,att:92,mid:91,def:91,identity:"Coragem e transição",core:"Madjer · Gomes · Sousa · João Pinto",colors:["#14529a","#f4efe2"]}];
